// WARNING: This file has automatically been generated on Sat, 20 Jul 2019 14:06:09 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <libxl.h>
#include <libxl_utils.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

