// WARNING: This file has automatically been generated on Mon, 15 Jul 2019 11:58:01 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <libxl.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

