// WARNING: This file has automatically been generated on Mon, 15 Jul 2019 11:58:01 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package libxl

/*
#cgo LDFLAGS: -L${SRCDIR}/../libxl -lxenlight
#include <libxl.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// havePhysinfoCapPv as defined in libxl/libxl.h:74
	havePhysinfoCapPv = 1
	// haveConsoleNotifyFd as defined in libxl/libxl.h:82
	haveConsoleNotifyFd = 1
	// haveConstCopyAndLengthFunctions as defined in libxl/libxl.h:89
	haveConstCopyAndLengthFunctions = 1
	// haveDomainNeedMemoryConstBInfo as defined in libxl/libxl.h:96
	haveDomainNeedMemoryConstBInfo = 1
	// haveVnuma as defined in libxl/libxl.h:103
	haveVnuma = 1
	// haveUserdataUnlink as defined in libxl/libxl.h:110
	haveUserdataUnlink = 1
	// haveCPUpoolQualifierToCPUpoolid as defined in libxl/libxl.h:119
	haveCPUpoolQualifierToCPUpoolid = 1
	// haveCPUpoolAddRemCPUmap as defined in libxl/libxl.h:128
	haveCPUpoolAddRemCPUmap = 1
	// haveBitmapAndOr as defined in libxl/libxl.h:137
	haveBitmapAndOr = 1
	// haveFirmwarePassthrough as defined in libxl/libxl.h:144
	haveFirmwarePassthrough = 1
	// haveDomainNodeaffinity as defined in libxl/libxl.h:151
	haveDomainNodeaffinity = 1
	// havePvusb as defined in libxl/libxl.h:157
	havePvusb = 1
	// haveBuildinfoHvmVendorDevice as defined in libxl/libxl.h:165
	haveBuildinfoHvmVendorDevice = 1
	// haveBuildinfoEventChannels as defined in libxl/libxl.h:170
	haveBuildinfoEventChannels = 1
	// haveBuildinfoHvmMsVmGenid as defined in libxl/libxl.h:175
	haveBuildinfoHvmMsVmGenid = 1
	// haveVCPUinfoSoftAffinity as defined in libxl/libxl.h:182
	haveVCPUinfoSoftAffinity = 1
	// haveSetVCPUaffinityForce as defined in libxl/libxl.h:188
	haveSetVCPUaffinityForce = 1
	// haveDeviceDiskDirectIoSafe as defined in libxl/libxl.h:195
	haveDeviceDiskDirectIoSafe = 1
	// haveDeviceDiskDiscardEnable as defined in libxl/libxl.h:200
	haveDeviceDiskDiscardEnable = 1
	// haveBuildinfoIomemStartGfn as defined in libxl/libxl.h:210
	haveBuildinfoIomemStartGfn = 1
	// haveSchedRtds as defined in libxl/libxl.h:216
	haveSchedRtds = 1
	// haveSchedNull as defined in libxl/libxl.h:222
	haveSchedNull = 1
	// haveBuildinfoHvmViridianEnableDisable as defined in libxl/libxl.h:228
	haveBuildinfoHvmViridianEnableDisable = 1
	// buildinfoHvmViridianEnableDisableWidth as defined in libxl/libxl.h:229
	buildinfoHvmViridianEnableDisableWidth = 64
	// haveBuildinfoHvmMmioHoleMemkb as defined in libxl/libxl.h:234
	haveBuildinfoHvmMmioHoleMemkb = 1
	// haveErrorDomainNotfound as defined in libxl/libxl.h:240
	haveErrorDomainNotfound = 1
	// haveDevicetreePassthrough as defined in libxl/libxl.h:246
	haveDevicetreePassthrough = 1
	// haveDeviceModelUser as defined in libxl/libxl.h:252
	haveDeviceModelUser = 1
	// haveVCPUSchedParams as defined in libxl/libxl.h:257
	haveVCPUSchedParams = 1
	// haveSchedRtdsVCPUParams as defined in libxl/libxl.h:263
	haveSchedRtdsVCPUParams = 1
	// haveSchedRtdsVCPUExtra as defined in libxl/libxl.h:269
	haveSchedRtdsVCPUExtra = 1
	// haveBuildinfoArmGicVersion as defined in libxl/libxl.h:274
	haveBuildinfoArmGicVersion = 1
	// haveSoftReset as defined in libxl/libxl.h:281
	haveSoftReset = 1
	// haveApicAssist as defined in libxl/libxl.h:287
	haveApicAssist = 1
	// haveBuildId as defined in libxl/libxl.h:293
	haveBuildId = 1
	// haveQemuMonitorCommand as defined in libxl/libxl.h:299
	haveQemuMonitorCommand = 1
	// haveSchedCredit2Params as defined in libxl/libxl.h:306
	haveSchedCredit2Params = 1
	// haveViridianCrashCtl as defined in libxl/libxl.h:319
	haveViridianCrashCtl = 1
	// haveBuildinfoHvmAcpiLaptopSlate as defined in libxl/libxl.h:325
	haveBuildinfoHvmAcpiLaptopSlate = 1
	// haveP9s as defined in libxl/libxl.h:330
	haveP9s = 1
	// haveBuildinfoArmVuart as defined in libxl/libxl.h:336
	haveBuildinfoArmVuart = 1
	// haveBuildinfoGrantLimits as defined in libxl/libxl.h:342
	haveBuildinfoGrantLimits = 1
	// maxGrantFramesDefault as defined in libxl/libxl.h:344
	maxGrantFramesDefault = 32
	// maxMaptrackFramesDefault as defined in libxl/libxl.h:345
	maxMaptrackFramesDefault = 1024
	// haveBuildinfoTimerMode as defined in libxl/libxl.h:357
	haveBuildinfoTimerMode = 1
	// haveBuildinfoApic as defined in libxl/libxl.h:358
	haveBuildinfoApic = 1
	// haveBuildinfoNestedHvm as defined in libxl/libxl.h:359
	haveBuildinfoNestedHvm = 1
	// haveBuildinfoBootloader as defined in libxl/libxl.h:360
	haveBuildinfoBootloader = 1
	// haveBuildinfoBootloaderArgs as defined in libxl/libxl.h:361
	haveBuildinfoBootloaderArgs = 1
	// haveExtendedVkb as defined in libxl/libxl.h:377
	haveExtendedVkb = 1
	// haveRetrieveDomainConfiguration as defined in libxl/libxl.h:615
	haveRetrieveDomainConfiguration = 1
	// haveBuildinfoVCPUAffinityArrays as defined in libxl/libxl.h:639
	haveBuildinfoVCPUAffinityArrays = 1
	// haveBuildinfoUsbdeviceList as defined in libxl/libxl.h:655
	haveBuildinfoUsbdeviceList = 1
	// haveBuildinfoUsbversion as defined in libxl/libxl.h:669
	haveBuildinfoUsbversion = 1
	// haveDeviceBackendDomname as defined in libxl/libxl.h:681
	haveDeviceBackendDomname = 1
	// haveNonconstEventOccursEventArg as defined in libxl/libxl.h:690
	haveNonconstEventOccursEventArg = 1
	// haveNonconstBasenameReturnValue as defined in libxl/libxl.h:700
	haveNonconstBasenameReturnValue = 1
	// havePhysinfoOutstandingPages as defined in libxl/libxl.h:710
	havePhysinfoOutstandingPages = 1
	// havePhysinfoMaxPossibleMfn as defined in libxl/libxl.h:719
	havePhysinfoMaxPossibleMfn = 1
	// haveDomInfoOutstandingMemkb as defined in libxl/libxl.h:728
	haveDomInfoOutstandingMemkb = 1
	// haveDomInfoNeverStop as defined in libxl/libxl.h:737
	haveDomInfoNeverStop = 1
	// haveQxl as defined in libxl/libxl.h:747
	haveQxl = 1
	// haveSpiceVdagent as defined in libxl/libxl.h:758
	haveSpiceVdagent = 1
	// haveSpiceUsbrediredirection as defined in libxl/libxl.h:769
	haveSpiceUsbrediredirection = 1
	// haveSpiceImagecompression as defined in libxl/libxl.h:780
	haveSpiceImagecompression = 1
	// haveSpiceStreamingvideo as defined in libxl/libxl.h:791
	haveSpiceStreamingvideo = 1
	// haveHvmHdtype as defined in libxl/libxl.h:799
	haveHvmHdtype = 1
	// haveDomainCreateRestoreParams as defined in libxl/libxl.h:807
	haveDomainCreateRestoreParams = 1
	// haveDomainCreateRestoreSendBackFd as defined in libxl/libxl.h:816
	haveDomainCreateRestoreSendBackFd = 1
	// haveDriverDomainCreation as defined in libxl/libxl.h:825
	haveDriverDomainCreation = 1
	// haveSigchldOwnerSelectiveReap as defined in libxl/libxl.h:838
	haveSigchldOwnerSelectiveReap = 1
	// haveSigchldSharing as defined in libxl/libxl.h:847
	haveSigchldSharing = 1
	// haveDomainSuspendOnly as defined in libxl/libxl.h:869
	haveDomainSuspendOnly = 1
	// haveDevicePciSeize as defined in libxl/libxl.h:879
	haveDevicePciSeize = 1
	// haveBuildinfoKernel as defined in libxl/libxl.h:894
	haveBuildinfoKernel = 1
	// haveDeviceChannel as defined in libxl/libxl.h:903
	haveDeviceChannel = 1
	// haveAoAbort as defined in libxl/libxl.h:908
	haveAoAbort = 1
	// haveUUIDCopyCtxParam as defined in libxl/libxl.h:923
	haveUUIDCopyCtxParam = 1
	// haveSsidLabel as defined in libxl/libxl.h:933
	haveSsidLabel = 1
	// haveCPUpoolName as defined in libxl/libxl.h:943
	haveCPUpoolName = 1
	// haveBuildinfoSerialList as defined in libxl/libxl.h:959
	haveBuildinfoSerialList = 1
	// haveAltp2m as defined in libxl/libxl.h:965
	haveAltp2m = 1
	// haveRemus as defined in libxl/libxl.h:971
	haveRemus = 1
	// haveColoUserspaceProxy as defined in libxl/libxl.h:977
	haveColoUserspaceProxy = 1
	// macFmt as defined in libxl/libxl.h:980
	macFmt = "%02hhx:%02hhx:%02hhx:%02hhx:%02hhx:%02hhx"
	// macFmtlen as defined in libxl/libxl.h:981
	macFmtlen = 17
	// havePsrCmt as defined in libxl/libxl.h:991
	havePsrCmt = 1
	// havePsrMbm as defined in libxl/libxl.h:998
	havePsrMbm = 1
	// havePsrCat as defined in libxl/libxl.h:1005
	havePsrCat = 1
	// havePsrCdp as defined in libxl/libxl.h:1012
	havePsrCdp = 1
	// havePsrL2Cat as defined in libxl/libxl.h:1019
	havePsrL2Cat = 1
	// havePsrGeneric as defined in libxl/libxl.h:1030
	havePsrGeneric = 1
	// haveMcaCaps as defined in libxl/libxl.h:1037
	haveMcaCaps = 1
	// havePcitopology as defined in libxl/libxl.h:1046
	havePcitopology = 1
	// haveSocketBitmap as defined in libxl/libxl.h:1054
	haveSocketBitmap = 1
	// haveSrmV2 as defined in libxl/libxl.h:1064
	haveSrmV2 = 1
	// haveSrmV1 as defined in libxl/libxl.h:1073
	haveSrmV1 = 1
	// haveCheckpointedStream as defined in libxl/libxl.h:1086
	haveCheckpointedStream = 1
	// haveVgaInterfaceTypeUnknown as defined in libxl/libxl.h:1116
	haveVgaInterfaceTypeUnknown = 1
	// haveBytearrayUUID as defined in libxl/libxl.h:1125
	haveBytearrayUUID = 1
	// haveMemkb64bits as defined in libxl/libxl.h:1136
	haveMemkb64bits = 1
	// haveQed as defined in libxl/libxl.h:1143
	haveQed = 1
	// haveSetParameters as defined in libxl/libxl.h:1150
	haveSetParameters = 1
	// havePvShim as defined in libxl/libxl.h:1158
	havePvShim = 1
	// havePvcalls as defined in libxl/libxl.h:1165
	havePvcalls = 1
	// pciFuncAll as defined in libxl/libxl.h:1204
	pciFuncAll = 4294967295
	// timerModeDefault as defined in libxl/libxl.h:1247
	timerModeDefault = -1
	// memkbDefault as defined in libxl/libxl.h:1248
	memkbDefault = 18446744073709551615
	// rdmMemBoundaryMemkbDefault as defined in libxl/libxl.h:1254
	rdmMemBoundaryMemkbDefault = 2097152
	// msVmGenidLen as defined in libxl/libxl.h:1256
	msVmGenidLen = 16
	// version as defined in libxl/libxl.h:1416
	version = 0
	// suspendDebug as defined in libxl/libxl.h:1514
	suspendDebug = 1
	// suspendLive as defined in libxl/libxl.h:1515
	suspendLive = 2
	// cputopologyInvalidEntry as defined in libxl/libxl.h:1702
	cputopologyInvalidEntry = (^(Uint32T)(0))
	// pcitopologyInvalidEntry as defined in libxl/libxl.h:1706
	pcitopologyInvalidEntry = (^(Uint32T)(0))
	// numainfoInvalidEntry as defined in libxl/libxl.h:1710
	numainfoInvalidEntry = (^(Uint32T)(0))
	// domainSchedParamWeightDefault as defined in libxl/libxl.h:2262
	domainSchedParamWeightDefault = -1
	// domainSchedParamCapDefault as defined in libxl/libxl.h:2263
	domainSchedParamCapDefault = -1
	// domainSchedParamPeriodDefault as defined in libxl/libxl.h:2264
	domainSchedParamPeriodDefault = -1
	// domainSchedParamSliceDefault as defined in libxl/libxl.h:2265
	domainSchedParamSliceDefault = -1
	// domainSchedParamLatencyDefault as defined in libxl/libxl.h:2266
	domainSchedParamLatencyDefault = -1
	// domainSchedParamExtratimeDefault as defined in libxl/libxl.h:2267
	domainSchedParamExtratimeDefault = -1
	// domainSchedParamBudgetDefault as defined in libxl/libxl.h:2268
	domainSchedParamBudgetDefault = -1
	// schedParamVCPUIndexDefault as defined in libxl/libxl.h:2271
	schedParamVCPUIndexDefault = -1
	// cpupoolPoolidAny as defined in libxl/libxl.h:2338
	cpupoolPoolidAny = 4294967295
	// uuidFmt as defined in include/libxl_uuid.h:18
	uuidFmt = "%02hhx%02hhx%02hhx%02hhx-%02hhx%02hhx-%02hhx%02hhx-%02hhx%02hhx-%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx"
	// uuidFmtlen as defined in include/libxl_uuid.h:19
	uuidFmtlen = 36
)

// XentoollogLevel as declared in include/xentoollog.h:42
type XentoollogLevel int32

// XentoollogLevel enumeration from include/xentoollog.h:42
const ()

// xlError as declared in libxl/_libxl_types.h:44
type xlError int32

// xlError enumeration from libxl/_libxl_types.h:44
const (
	errorNonspecific                  xlError = -1
	errorVersion                      xlError = -2
	errorFail                         xlError = -3
	errorNi                           xlError = -4
	errorNomem                        xlError = -5
	errorInval                        xlError = -6
	errorBadfail                      xlError = -7
	errorGuestTimedout                xlError = -8
	errorTimedout                     xlError = -9
	errorNoparavirt                   xlError = -10
	errorNotReady                     xlError = -11
	errorOseventRegFail               xlError = -12
	errorBufferfull                   xlError = -13
	errorUnknownChild                 xlError = -14
	errorLockFail                     xlError = -15
	errorJsonConfigEmpty              xlError = -16
	errorDeviceExists                 xlError = -17
	errorCheckpointDevopsDoesNotMatch xlError = -18
	errorCheckpointDeviceNotSupported xlError = -19
	errorVnumaConfigInvalid           xlError = -20
	errorDomainNotfound               xlError = -21
	errorAborted                      xlError = -22
	errorNotfound                     xlError = -23
	errorDomainDestroyed              xlError = -24
	errorFeatureRemoved               xlError = -25
	errorProtocolErrorQmp             xlError = -26
	errorUnknownQmpError              xlError = -27
	errorQmpGenericError              xlError = -28
	errorQmpCommandNotFound           xlError = -29
	errorQmpDeviceNotActive           xlError = -30
	errorQmpDeviceNotFound            xlError = -31
	errorQemuApi                      xlError = -32
)

// DomainType as declared in libxl/_libxl_types.h:56
type DomainType int32

// DomainType enumeration from libxl/_libxl_types.h:56
const (
	domainTypeInvalid DomainType = -1
	domainTypeHvm     DomainType = 1
	domainTypePv      DomainType = 2
	domainTypePvh     DomainType = 3
)

// ChannelConnection as declared in libxl/_libxl_types.h:88
type ChannelConnection int32

// ChannelConnection enumeration from libxl/_libxl_types.h:88
const (
	channelConnectionUnknown ChannelConnection = iota
	channelConnectionPty     ChannelConnection = 1
	channelConnectionSocket  ChannelConnection = 2
)

// ActionOnShutdown as declared in libxl/_libxl_types.h:164
type ActionOnShutdown int32

// ActionOnShutdown enumeration from libxl/_libxl_types.h:164
const (
	actionOnShutdownDestroy         ActionOnShutdown = 1
	actionOnShutdownRestart         ActionOnShutdown = 2
	actionOnShutdownRestartRename   ActionOnShutdown = 3
	actionOnShutdownPreserve        ActionOnShutdown = 4
	actionOnShutdownCoredumpDestroy ActionOnShutdown = 5
	actionOnShutdownCoredumpRestart ActionOnShutdown = 6
	actionOnShutdownSoftReset       ActionOnShutdown = 7
)

const ()

const ()

const ()

const ()

const ()

const ()

// SocketType as declared in bits/socket_type.h:24
type SocketType int32

// SocketType enumeration from bits/socket_type.h:24
const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

// ItimerWhich as declared in sys/time.h:88
type ItimerWhich int32

// ItimerWhich enumeration from sys/time.h:88
const ()
