// WARNING: This file has automatically been generated on Sat, 20 Jul 2019 14:06:09 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package libxl

/*
#cgo LDFLAGS: -L${SRCDIR}/../libxl -lxenlight
#include <libxl.h>
#include <libxl_utils.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// havePhysinfoCapPv as defined in libxl/libxl.h:74
	havePhysinfoCapPv = 1
	// haveConsoleNotifyFd as defined in libxl/libxl.h:82
	haveConsoleNotifyFd = 1
	// haveConstCopyAndLengthFunctions as defined in libxl/libxl.h:89
	haveConstCopyAndLengthFunctions = 1
	// haveDomainNeedMemoryConstBInfo as defined in libxl/libxl.h:96
	haveDomainNeedMemoryConstBInfo = 1
	// haveVnuma as defined in libxl/libxl.h:103
	haveVnuma = 1
	// haveUserdataUnlink as defined in libxl/libxl.h:110
	haveUserdataUnlink = 1
	// haveCPUpoolQualifierToCPUpoolid as defined in libxl/libxl.h:119
	haveCPUpoolQualifierToCPUpoolid = 1
	// haveCPUpoolAddRemCPUmap as defined in libxl/libxl.h:128
	haveCPUpoolAddRemCPUmap = 1
	// haveBitmapAndOr as defined in libxl/libxl.h:137
	haveBitmapAndOr = 1
	// haveFirmwarePassthrough as defined in libxl/libxl.h:144
	haveFirmwarePassthrough = 1
	// haveDomainNodeaffinity as defined in libxl/libxl.h:151
	haveDomainNodeaffinity = 1
	// havePvusb as defined in libxl/libxl.h:157
	havePvusb = 1
	// haveBuildinfoHvmVendorDevice as defined in libxl/libxl.h:165
	haveBuildinfoHvmVendorDevice = 1
	// haveBuildinfoEventChannels as defined in libxl/libxl.h:170
	haveBuildinfoEventChannels = 1
	// haveBuildinfoHvmMsVmGenid as defined in libxl/libxl.h:175
	haveBuildinfoHvmMsVmGenid = 1
	// haveVCPUinfoSoftAffinity as defined in libxl/libxl.h:182
	haveVCPUinfoSoftAffinity = 1
	// haveSetVCPUaffinityForce as defined in libxl/libxl.h:188
	haveSetVCPUaffinityForce = 1
	// haveDeviceDiskDirectIoSafe as defined in libxl/libxl.h:195
	haveDeviceDiskDirectIoSafe = 1
	// haveDeviceDiskDiscardEnable as defined in libxl/libxl.h:200
	haveDeviceDiskDiscardEnable = 1
	// haveBuildinfoIomemStartGfn as defined in libxl/libxl.h:210
	haveBuildinfoIomemStartGfn = 1
	// haveSchedRtds as defined in libxl/libxl.h:216
	haveSchedRtds = 1
	// haveSchedNull as defined in libxl/libxl.h:222
	haveSchedNull = 1
	// haveBuildinfoHvmViridianEnableDisable as defined in libxl/libxl.h:228
	haveBuildinfoHvmViridianEnableDisable = 1
	// buildinfoHvmViridianEnableDisableWidth as defined in libxl/libxl.h:229
	buildinfoHvmViridianEnableDisableWidth = 64
	// haveBuildinfoHvmMmioHoleMemkb as defined in libxl/libxl.h:234
	haveBuildinfoHvmMmioHoleMemkb = 1
	// haveErrorDomainNotfound as defined in libxl/libxl.h:240
	haveErrorDomainNotfound = 1
	// haveDevicetreePassthrough as defined in libxl/libxl.h:246
	haveDevicetreePassthrough = 1
	// haveDeviceModelUser as defined in libxl/libxl.h:252
	haveDeviceModelUser = 1
	// haveVCPUSchedParams as defined in libxl/libxl.h:257
	haveVCPUSchedParams = 1
	// haveSchedRtdsVCPUParams as defined in libxl/libxl.h:263
	haveSchedRtdsVCPUParams = 1
	// haveSchedRtdsVCPUExtra as defined in libxl/libxl.h:269
	haveSchedRtdsVCPUExtra = 1
	// haveBuildinfoArmGicVersion as defined in libxl/libxl.h:274
	haveBuildinfoArmGicVersion = 1
	// haveSoftReset as defined in libxl/libxl.h:281
	haveSoftReset = 1
	// haveApicAssist as defined in libxl/libxl.h:287
	haveApicAssist = 1
	// haveBuildId as defined in libxl/libxl.h:293
	haveBuildId = 1
	// haveQemuMonitorCommand as defined in libxl/libxl.h:299
	haveQemuMonitorCommand = 1
	// haveSchedCredit2Params as defined in libxl/libxl.h:306
	haveSchedCredit2Params = 1
	// haveViridianCrashCtl as defined in libxl/libxl.h:319
	haveViridianCrashCtl = 1
	// haveViridianSynic as defined in libxl/libxl.h:325
	haveViridianSynic = 1
	// haveViridianStimer as defined in libxl/libxl.h:331
	haveViridianStimer = 1
	// haveViridianHcallIpi as defined in libxl/libxl.h:337
	haveViridianHcallIpi = 1
	// haveBuildinfoHvmAcpiLaptopSlate as defined in libxl/libxl.h:343
	haveBuildinfoHvmAcpiLaptopSlate = 1
	// haveP9s as defined in libxl/libxl.h:348
	haveP9s = 1
	// haveBuildinfoArmVuart as defined in libxl/libxl.h:354
	haveBuildinfoArmVuart = 1
	// haveBuildinfoGrantLimits as defined in libxl/libxl.h:360
	haveBuildinfoGrantLimits = 1
	// maxGrantFramesDefault as defined in libxl/libxl.h:362
	maxGrantFramesDefault = 32
	// maxMaptrackFramesDefault as defined in libxl/libxl.h:363
	maxMaptrackFramesDefault = 1024
	// haveBuildinfoTimerMode as defined in libxl/libxl.h:375
	haveBuildinfoTimerMode = 1
	// haveBuildinfoApic as defined in libxl/libxl.h:376
	haveBuildinfoApic = 1
	// haveBuildinfoNestedHvm as defined in libxl/libxl.h:377
	haveBuildinfoNestedHvm = 1
	// haveBuildinfoBootloader as defined in libxl/libxl.h:378
	haveBuildinfoBootloader = 1
	// haveBuildinfoBootloaderArgs as defined in libxl/libxl.h:379
	haveBuildinfoBootloaderArgs = 1
	// haveExtendedVkb as defined in libxl/libxl.h:395
	haveExtendedVkb = 1
	// haveRetrieveDomainConfiguration as defined in libxl/libxl.h:633
	haveRetrieveDomainConfiguration = 1
	// haveBuildinfoVCPUAffinityArrays as defined in libxl/libxl.h:657
	haveBuildinfoVCPUAffinityArrays = 1
	// haveBuildinfoVkbDevice as defined in libxl/libxl.h:666
	haveBuildinfoVkbDevice = 1
	// haveBuildinfoUsbdeviceList as defined in libxl/libxl.h:682
	haveBuildinfoUsbdeviceList = 1
	// haveBuildinfoUsbversion as defined in libxl/libxl.h:696
	haveBuildinfoUsbversion = 1
	// haveDeviceBackendDomname as defined in libxl/libxl.h:708
	haveDeviceBackendDomname = 1
	// haveNonconstEventOccursEventArg as defined in libxl/libxl.h:717
	haveNonconstEventOccursEventArg = 1
	// haveNonconstBasenameReturnValue as defined in libxl/libxl.h:727
	haveNonconstBasenameReturnValue = 1
	// havePhysinfoOutstandingPages as defined in libxl/libxl.h:737
	havePhysinfoOutstandingPages = 1
	// havePhysinfoMaxPossibleMfn as defined in libxl/libxl.h:746
	havePhysinfoMaxPossibleMfn = 1
	// haveDomInfoOutstandingMemkb as defined in libxl/libxl.h:755
	haveDomInfoOutstandingMemkb = 1
	// haveDomInfoNeverStop as defined in libxl/libxl.h:764
	haveDomInfoNeverStop = 1
	// haveQxl as defined in libxl/libxl.h:774
	haveQxl = 1
	// haveSpiceVdagent as defined in libxl/libxl.h:785
	haveSpiceVdagent = 1
	// haveSpiceUsbrediredirection as defined in libxl/libxl.h:796
	haveSpiceUsbrediredirection = 1
	// haveSpiceImagecompression as defined in libxl/libxl.h:807
	haveSpiceImagecompression = 1
	// haveSpiceStreamingvideo as defined in libxl/libxl.h:818
	haveSpiceStreamingvideo = 1
	// haveHvmHdtype as defined in libxl/libxl.h:826
	haveHvmHdtype = 1
	// haveDomainCreateRestoreParams as defined in libxl/libxl.h:834
	haveDomainCreateRestoreParams = 1
	// haveDomainCreateRestoreSendBackFd as defined in libxl/libxl.h:843
	haveDomainCreateRestoreSendBackFd = 1
	// haveDriverDomainCreation as defined in libxl/libxl.h:852
	haveDriverDomainCreation = 1
	// haveSigchldOwnerSelectiveReap as defined in libxl/libxl.h:865
	haveSigchldOwnerSelectiveReap = 1
	// haveSigchldSharing as defined in libxl/libxl.h:874
	haveSigchldSharing = 1
	// haveDomainSuspendOnly as defined in libxl/libxl.h:896
	haveDomainSuspendOnly = 1
	// haveDevicePciSeize as defined in libxl/libxl.h:906
	haveDevicePciSeize = 1
	// haveBuildinfoKernel as defined in libxl/libxl.h:921
	haveBuildinfoKernel = 1
	// haveDeviceChannel as defined in libxl/libxl.h:930
	haveDeviceChannel = 1
	// haveAoAbort as defined in libxl/libxl.h:935
	haveAoAbort = 1
	// haveUUIDCopyCtxParam as defined in libxl/libxl.h:950
	haveUUIDCopyCtxParam = 1
	// haveSsidLabel as defined in libxl/libxl.h:960
	haveSsidLabel = 1
	// haveCPUpoolName as defined in libxl/libxl.h:970
	haveCPUpoolName = 1
	// haveBuildinfoSerialList as defined in libxl/libxl.h:986
	haveBuildinfoSerialList = 1
	// haveAltp2m as defined in libxl/libxl.h:992
	haveAltp2m = 1
	// haveRemus as defined in libxl/libxl.h:998
	haveRemus = 1
	// haveColoUserspaceProxy as defined in libxl/libxl.h:1004
	haveColoUserspaceProxy = 1
	// macFmt as defined in libxl/libxl.h:1007
	macFmt = "%02hhx:%02hhx:%02hhx:%02hhx:%02hhx:%02hhx"
	// macFmtlen as defined in libxl/libxl.h:1008
	macFmtlen = 17
	// havePsrCmt as defined in libxl/libxl.h:1018
	havePsrCmt = 1
	// havePsrMbm as defined in libxl/libxl.h:1025
	havePsrMbm = 1
	// havePsrCat as defined in libxl/libxl.h:1032
	havePsrCat = 1
	// havePsrCdp as defined in libxl/libxl.h:1039
	havePsrCdp = 1
	// havePsrL2Cat as defined in libxl/libxl.h:1046
	havePsrL2Cat = 1
	// havePsrGeneric as defined in libxl/libxl.h:1057
	havePsrGeneric = 1
	// haveMcaCaps as defined in libxl/libxl.h:1064
	haveMcaCaps = 1
	// havePcitopology as defined in libxl/libxl.h:1073
	havePcitopology = 1
	// haveSocketBitmap as defined in libxl/libxl.h:1081
	haveSocketBitmap = 1
	// haveSrmV2 as defined in libxl/libxl.h:1091
	haveSrmV2 = 1
	// haveSrmV1 as defined in libxl/libxl.h:1100
	haveSrmV1 = 1
	// haveCheckpointedStream as defined in libxl/libxl.h:1113
	haveCheckpointedStream = 1
	// haveVgaInterfaceTypeUnknown as defined in libxl/libxl.h:1143
	haveVgaInterfaceTypeUnknown = 1
	// haveBytearrayUUID as defined in libxl/libxl.h:1152
	haveBytearrayUUID = 1
	// haveMemkb64bits as defined in libxl/libxl.h:1163
	haveMemkb64bits = 1
	// haveQed as defined in libxl/libxl.h:1170
	haveQed = 1
	// haveSetParameters as defined in libxl/libxl.h:1177
	haveSetParameters = 1
	// havePvShim as defined in libxl/libxl.h:1185
	havePvShim = 1
	// havePvcalls as defined in libxl/libxl.h:1192
	havePvcalls = 1
	// pciFuncAll as defined in libxl/libxl.h:1231
	pciFuncAll = 4294967295
	// timerModeDefault as defined in libxl/libxl.h:1274
	timerModeDefault = -1
	// memkbDefault as defined in libxl/libxl.h:1275
	memkbDefault = 18446744073709551615
	// rdmMemBoundaryMemkbDefault as defined in libxl/libxl.h:1281
	rdmMemBoundaryMemkbDefault = 2097152
	// msVmGenidLen as defined in libxl/libxl.h:1283
	msVmGenidLen = 16
	// version as defined in libxl/libxl.h:1443
	version = 0
	// suspendDebug as defined in libxl/libxl.h:1541
	suspendDebug = 1
	// suspendLive as defined in libxl/libxl.h:1542
	suspendLive = 2
	// cputopologyInvalidEntry as defined in libxl/libxl.h:1729
	cputopologyInvalidEntry = (^(Uint32T)(0))
	// pcitopologyInvalidEntry as defined in libxl/libxl.h:1733
	pcitopologyInvalidEntry = (^(Uint32T)(0))
	// numainfoInvalidEntry as defined in libxl/libxl.h:1737
	numainfoInvalidEntry = (^(Uint32T)(0))
	// domainSchedParamWeightDefault as defined in libxl/libxl.h:2289
	domainSchedParamWeightDefault = -1
	// domainSchedParamCapDefault as defined in libxl/libxl.h:2290
	domainSchedParamCapDefault = -1
	// domainSchedParamPeriodDefault as defined in libxl/libxl.h:2291
	domainSchedParamPeriodDefault = -1
	// domainSchedParamSliceDefault as defined in libxl/libxl.h:2292
	domainSchedParamSliceDefault = -1
	// domainSchedParamLatencyDefault as defined in libxl/libxl.h:2293
	domainSchedParamLatencyDefault = -1
	// domainSchedParamExtratimeDefault as defined in libxl/libxl.h:2294
	domainSchedParamExtratimeDefault = -1
	// domainSchedParamBudgetDefault as defined in libxl/libxl.h:2295
	domainSchedParamBudgetDefault = -1
	// schedParamVCPUIndexDefault as defined in libxl/libxl.h:2298
	schedParamVCPUIndexDefault = -1
	// cpupoolPoolidAny as defined in libxl/libxl.h:2365
	cpupoolPoolidAny = 4294967295
	// uuidFmt as defined in include/libxl_uuid.h:18
	uuidFmt = "%02hhx%02hhx%02hhx%02hhx-%02hhx%02hhx-%02hhx%02hhx-%02hhx%02hhx-%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx"
	// uuidFmtlen as defined in include/libxl_uuid.h:19
	uuidFmtlen = 36
)

// XentoollogLevel as declared in include/xentoollog.h:42
type XentoollogLevel int32

// XentoollogLevel enumeration from include/xentoollog.h:42
const ()

// xlError as declared in libxl/_libxl_types.h:44
type xlError int32

// xlError enumeration from libxl/_libxl_types.h:44
const (
	errorNonspecific                  xlError = -1
	errorVersion                      xlError = -2
	errorFail                         xlError = -3
	errorNi                           xlError = -4
	errorNomem                        xlError = -5
	errorInval                        xlError = -6
	errorBadfail                      xlError = -7
	errorGuestTimedout                xlError = -8
	errorTimedout                     xlError = -9
	errorNoparavirt                   xlError = -10
	errorNotReady                     xlError = -11
	errorOseventRegFail               xlError = -12
	errorBufferfull                   xlError = -13
	errorUnknownChild                 xlError = -14
	errorLockFail                     xlError = -15
	errorJsonConfigEmpty              xlError = -16
	errorDeviceExists                 xlError = -17
	errorCheckpointDevopsDoesNotMatch xlError = -18
	errorCheckpointDeviceNotSupported xlError = -19
	errorVnumaConfigInvalid           xlError = -20
	errorDomainNotfound               xlError = -21
	errorAborted                      xlError = -22
	errorNotfound                     xlError = -23
	errorDomainDestroyed              xlError = -24
	errorFeatureRemoved               xlError = -25
	errorProtocolErrorQmp             xlError = -26
	errorUnknownQmpError              xlError = -27
	errorQmpGenericError              xlError = -28
	errorQmpCommandNotFound           xlError = -29
	errorQmpDeviceNotActive           xlError = -30
	errorQmpDeviceNotFound            xlError = -31
	errorQemuApi                      xlError = -32
)

// DomainType as declared in libxl/_libxl_types.h:56
type DomainType int32

// DomainType enumeration from libxl/_libxl_types.h:56
const (
	domainTypeInvalid DomainType = -1
	domainTypeHvm     DomainType = 1
	domainTypePv      DomainType = 2
	domainTypePvh     DomainType = 3
)

// ChannelConnection as declared in libxl/_libxl_types.h:88
type ChannelConnection int32

// ChannelConnection enumeration from libxl/_libxl_types.h:88
const (
	channelConnectionUnknown ChannelConnection = iota
	channelConnectionPty     ChannelConnection = 1
	channelConnectionSocket  ChannelConnection = 2
)

// ActionOnShutdown as declared in libxl/_libxl_types.h:164
type ActionOnShutdown int32

// ActionOnShutdown enumeration from libxl/_libxl_types.h:164
const (
	actionOnShutdownDestroy         ActionOnShutdown = 1
	actionOnShutdownRestart         ActionOnShutdown = 2
	actionOnShutdownRestartRename   ActionOnShutdown = 3
	actionOnShutdownPreserve        ActionOnShutdown = 4
	actionOnShutdownCoredumpDestroy ActionOnShutdown = 5
	actionOnShutdownCoredumpRestart ActionOnShutdown = 6
	actionOnShutdownSoftReset       ActionOnShutdown = 7
)

const ()

const ()

const ()

const ()

const ()

const ()

// SocketType as declared in bits/socket_type.h:24
type SocketType int32

// SocketType enumeration from bits/socket_type.h:24
const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

// CodecvtResult as declared in bits/libio.h:180
type CodecvtResult int32

// CodecvtResult enumeration from bits/libio.h:180
const ()

// ItimerWhich as declared in sys/time.h:88
type ItimerWhich int32

// ItimerWhich enumeration from sys/time.h:88
const ()
