// WARNING: This file has automatically been generated on Mon, 15 Jul 2019 11:58:01 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package libxl provides Go bindings for the Xen Project hypervisor's libxenlight (libxl).
*/
package libxl
