// WARNING: This file has automatically been generated on Sat, 20 Jul 2019 14:06:09 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package libxl provides Go bindings for the Xen Project hypervisor's libxenlight (libxl).
*/
package libxl
