// WARNING: This file has automatically been generated on Sat, 20 Jul 2019 14:06:09 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package libxl

/*
#cgo LDFLAGS: -L${SRCDIR}/../libxl -lxenlight
#include <libxl.h>
#include <libxl_utils.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Ctx as declared in libxl/libxl.h:614
type Ctx C.libxl_ctx

// KeyValueList type as declared in libxl/libxl.h:1200
type KeyValueList [][]byte

// DomID type as declared in libxl/libxl.h:1233
type DomID uint32

// DevID type as declared in libxl/libxl.h:1234
type DevID int32

// Defbool as declared in libxl/libxl.h:1261
type Defbool C.libxl_defbool

// AsyncopHow as declared in libxl/libxl.h:1342
type AsyncopHow C.libxl_asyncop_how

// AsyncprogressHow as declared in libxl/libxl.h:1388
type AsyncprogressHow C.libxl_asyncprogress_how

// Uint32T type as declared in bits/stdint-uintn.h:26
type Uint32T uint32

// XentoollogLogger as declared in include/xentoollog.h:44
type XentoollogLogger C.xentoollog_logger

// XentoollogLoggerStdiostream as declared in include/xentoollog.h:73
type XentoollogLoggerStdiostream C.xentoollog_logger_stdiostream

// UUID as declared in include/libxl_uuid.h:29
type UUID C.libxl_uuid

// DomInfo as declared in libxl/_libxl_types.h:443
type DomInfo struct {
	UUID             UUID
	DomID            DomID
	Ssidref          Uint32T
	SsidLabel        []byte
	Running          bool
	Blocked          bool
	Paused           bool
	Shutdown         bool
	Dying            bool
	NeverStop        bool
	OutstandingMemkb uint
	CurrentMemkb     uint
	SharedMemkb      uint
	PagedMemkb       uint
	MaxMemkb         uint
	CPUTime          uint
	VCPUMaxId        Uint32T
	VCPUOnline       Uint32T
	CPUpool          Uint32T
	DomainType       DomainType
	reff885823f      *C.libxl_dominfo
	allocsf885823f   interface{}
}

// DomainCreateInfo as declared in libxl/_libxl_types.h:531
type DomainCreateInfo C.libxl_domain_create_info

// DomainBuildInfo as declared in libxl/_libxl_types.h:764
type DomainBuildInfo C.libxl_domain_build_info

// DeviceVfb as declared in libxl/_libxl_types.h:780
type DeviceVfb C.libxl_device_vfb

// DeviceVkb as declared in libxl/_libxl_types.h:803
type DeviceVkb C.libxl_device_vkb

// DeviceDisk as declared in libxl/_libxl_types.h:830
type DeviceDisk C.libxl_device_disk

// DeviceNic as declared in libxl/_libxl_types.h:901
type DeviceNic C.libxl_device_nic

// DevicePci as declared in libxl/_libxl_types.h:920
type DevicePci C.libxl_device_pci

// DeviceRdm as declared in libxl/_libxl_types.h:931
type DeviceRdm C.libxl_device_rdm

// DeviceUsbctrl as declared in libxl/_libxl_types.h:966
type DeviceUsbctrl C.libxl_device_usbctrl

// DeviceUsbdev as declared in libxl/_libxl_types.h:981
type DeviceUsbdev C.libxl_device_usbdev

// DeviceDtdev as declared in libxl/_libxl_types.h:991
type DeviceDtdev C.libxl_device_dtdev

// DeviceVtpm as declared in libxl/_libxl_types.h:1003
type DeviceVtpm C.libxl_device_vtpm

// DeviceP9 as declared in libxl/_libxl_types.h:1017
type DeviceP9 C.libxl_device_p9

// DevicePvcallsif as declared in libxl/_libxl_types.h:1028
type DevicePvcallsif C.libxl_device_pvcallsif

// DeviceChannel as declared in libxl/_libxl_types.h:1046
type DeviceChannel C.libxl_device_channel

// DeviceVdispl as declared in libxl/_libxl_types.h:1072
type DeviceVdispl C.libxl_device_vdispl

// DeviceVsnd as declared in libxl/_libxl_types.h:1169
type DeviceVsnd C.libxl_device_vsnd

// DomainConfig as declared in libxl/_libxl_types.h:1214
type DomainConfig struct {
	CInfo          DomainCreateInfo
	BInfo          DomainBuildInfo
	NumDisks       int32
	Disks          *DeviceDisk
	NumNics        int32
	Nics           *DeviceNic
	NumPcidevs     int32
	Pcidevs        *DevicePci
	NumRdms        int32
	Rdms           *DeviceRdm
	NumDtdevs      int32
	Dtdevs         *DeviceDtdev
	NumVfbs        int32
	Vfbs           *DeviceVfb
	NumVkbs        int32
	Vkbs           *DeviceVkb
	NumVtpms       int32
	Vtpms          *DeviceVtpm
	NumP9s         int32
	P9s            *DeviceP9
	NumPvcallsifs  int32
	Pvcallsifs     *DevicePvcallsif
	NumVdispls     int32
	Vdispls        *DeviceVdispl
	NumVsnds       int32
	Vsnds          *DeviceVsnd
	NumChannels    int32
	Channels       *DeviceChannel
	NumUsbctrls    int32
	Usbctrls       *DeviceUsbctrl
	NumUsbdevs     int32
	Usbdevs        *DeviceUsbdev
	OnPoweroff     ActionOnShutdown
	OnReboot       ActionOnShutdown
	OnWatchdog     ActionOnShutdown
	OnCrash        ActionOnShutdown
	OnSoftReset    ActionOnShutdown
	ref87e08e4d    *C.libxl_domain_config
	allocs87e08e4d interface{}
}
